version: "3.9"

services:
  java-api01:
    image: marcelobruckner/rinha-spring-java-api:latest
    hostname: java-api01
    environment:
      - SERVER_PORT=8000
      - DATABASE_URL=jdbc:postgresql://db-postgresql:5432/rinhadb
      - DATABASE_USERNAME=admin
      - DATABASE_PASSWORD=admin
    depends_on:
      db-postgresql:
        condition: service_healthy
    ulimits:
      nofile:
        soft: 1000000
        hard: 1000000
    deploy:
      resources:
        limits:
          cpus: "0.3"
          memory: "960MB"
    networks:
      - app-network

  java-api02:
    image: marcelobruckner/rinha-spring-java-api:latest
    hostname: java-api01
    environment:
      - SERVER_PORT=8000
      - DATABASE_URL=jdbc:postgresql://db-postgresql:5432/rinhadb
      - DATABASE_USERNAME=admin
      - DATABASE_PASSWORD=admin
    depends_on:
      db-postgresql:
        condition: service_healthy
    ulimits:
      nofile:
        soft: 1000000
        hard: 1000000
    deploy:
      resources:
        limits:
          cpus: "0.3"
          memory: "960MB"
    networks:
      - app-network

  db-postgresql:
    image: postgres:latest
    command: "postgres -c max_connections=200 -c shared_buffers=256MB -c synchronous_commit=off -c fsync=off -c full_page_writes=off"
    hostname: db-postgresql
    environment:
      - POSTGRES_PASSWORD=admin
      - POSTGRES_USER=admin
      - POSTGRES_DB=rinhadb
    ports:
      - "5432:5432"
    deploy:
      resources:
        limits:
          cpus: "0.8"
          memory: "1GB"
    networks:
      - app-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 5s
      timeout: 5s
      retries: 20
      start_period: 10s

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - java-api01
      - java-api02
    ports:
      - "9999:9999"
    deploy:
      resources:
        limits:
          cpus: "0.1"
          memory: "128MB"
    networks:
      - app-network
networks:
  app-network:
